# Header
menu:
  主页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
#- category
- tag
#- tagcloud
- archive
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Links
links:
  丹妮妮: https://chendanni.github.io/
  陈云龙大神~: http://www.cylong.com/
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com  

# M
# Miscellaneous
google_analytics: true
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Baidu share
#baidushare: true

cnzz_tongji:
  enable: true
  siteid: 1260398845
