# Header
menu:
  主页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
#- category
- tag
#- tagcloud
- archive
- links

# Links
links:
  丹妮妮: https://chendanni.github.io/
  陈云龙大神~: http://www.cylong.com/
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com  

# Miscellaneous
google_analytics: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: 

# Baidu share
baidushare: true

cnzz_tongji:
  enable: true
  siteid: 1260398845  ## e.g. 1253575964 your cnzz tongji site id
#mathjax - 是否开启latex数学公式
#links - 友情链接
#duoshuo_shortname - 多说评论id
#baidushare - 是否开启百度分享
